#[derive(Debug)]
#[allow(dead_code)]
pub enum Commands {
    Play {
        input: String,
        decoder: Option<String>,
        no_audio: bool,
        loop_video: bool,
    },
    Transcode {
        input: String,
        output: String,
        codec: String,
        preset: String,
        bitrate: Option<String>,
        scale: Option<String>,
        transcode_audio: bool,
        audio_codec: Option<String>,
    },
    Screenshot {
        input: String,
        output: String,
        time_ms: u32,
    },
    Subtitle {
        input: String,
        output: String,
        operation: String,
        sub_file: Option<String>,
        shift_ms: Option<i32>,
        track_index: Option<u32>,
    },
    Edit {
        input: String,
        output: String,
        operation: String,
        start_time: Option<String>,
        end_time: Option<String>,
        duration: Option<String>,
        crop: Option<String>,
        rotate: Option<String>,
        flip: Option<String>,
        scale: Option<String>,
        loop_count: Option<i32>,
        fade_in: Option<String>,
        fade_out: Option<String>,
        overlay_file: Option<String>,
        watermark_text: Option<String>,
        position: Option<String>,
        additional_inputs: Vec<String>,
    },
    Color {
        input: String,
        output: String,
        operation: String,
        lut_file: Option<String>,
        gamma: Option<String>,
        shadows: Option<String>,
        midtones: Option<String>,
        highlights: Option<String>,
        colorspace: Option<String>,
        temperature: Option<f32>,
        brightness: Option<f32>,
        contrast: Option<f32>,
        saturation: Option<f32>,
        tonemap: Option<String>,
    },
    Audio {
        input: String,
        output: String,
        operation: String,
        volume: Option<String>,
        noise_reduction: Option<String>,
        threshold: Option<String>,
        ratio: Option<String>,
        limit: Option<String>,
        gain: Option<String>,
        frequency: Option<String>,
        pitch: Option<f32>,
        tempo: Option<f32>,
        loudness: Option<String>,
        silence_db: Option<String>,
        silence_duration: Option<String>,
    },
    Info,
    Record {
        output: String,
        fps: Option<u32>,
        bitrate: Option<String>,
        duration_sec: Option<u32>,
    },
    Overlay {
        input: String,
        output: String,
        overlay_file: String,
        position: Option<String>,
        overlay_type: Option<String>,
    },
    Shader {
        input: String,
        output: String,
        shader_file: String,
    },
    Mux {
        video_input: String,
        audio_input: String,
        output: String,
    },
}
